### ISSUE TITLE
Why this example will not work

### ISSUE THREAD

**Issue by pyed** [Syfaro/telegram-bot-api#12]
our project is `github.com/pyed/example` contains one package `telegram` that uses `telegram-bot-api` and a `main.go`

```
$GOPATH/src/github.com/pyed/example
├── main.go
└── telegram
    └── telegram.go
```

`telegram/telegram.go`
``` Go
package telegram

import (
	"log"

	"github.com/Syfaro/telegram-bot-api"
)

var Bot *tgbotapi.BotAPI

func init() {
	Bot, err := tgbotapi.NewBotAPI("MyAwesomeBotToken")
	if err != nil {
		log.Panic(err)
	}

	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60

	err = Bot.UpdatesChan(u)
	if err != nil {
		log.Panic(err)
	}

	log.Printf("Authorized on account %s", Bot.Self.UserName)
}
```

`example/main.go`

``` Go
package main

import (
	"log"

	"github.com/pyed/example/telegram"
)

func main() {
	for update := range telegram.Bot.Updates {
		log.Printf("[%s] %s", update.Message.From.UserName, update.Message.Text)
	}
}

```

trying to `go run main.go` will produce the following

```
2015/08/07 07:41:47 Authorized on account myawesomebot
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x2038]

goroutine 1 [running]:
main.main()
	$GOPATH/src/github.com/pyed/example/main.go:10 +0x38

goroutine 1 [select]:
net/http.(*persistConn).roundTrip(0xc20806e000, 0xc208267640, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc208064000, 0xc208033930, 0xc20826b6e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:235 +0x558
net/http.send(0xc208033930, 0x611cd8, 0xc208064000, 0x54, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc20803a9f0, 0xc208033930, 0x54, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc20803a9f0, 0xc208033930, 0x367330, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:367 +0xb25
net/http.(*Client).Post(0xc20803a9f0, 0xc20826b680, 0x54, 0x327210, 0x21, 0x611d28, 0xc20825f9a0, 0x54, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:441 +0x10d
net/http.(*Client).PostForm(0xc20803a9f0, 0xc20826b680, 0x54, 0xc2081eefc0, 0x2, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:461 +0x11c
github.com/Syfaro/telegram-bot-api.(*BotAPI).MakeRequest(0xc208058060, 0x2f33b0, 0xa, 0xc2081eefc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	$GOPATH/src/github.com/Syfaro/telegram-bot-api/methods.go:150 +0x1ee
github.com/Syfaro/telegram-bot-api.(*BotAPI).GetUpdates(0xc208058060, 0x0, 0x0, 0x3c, 0x0, 0x0, 0x0, 0x0, 0x0)
	$GOPATH/src/github.com/Syfaro/telegram-bot-api/methods.go:771 +0x671
github.com/Syfaro/telegram-bot-api.func·001()
	$GOPATH/src/github.com/Syfaro/telegram-bot-api/updates.go:14 +0x58
created by github.com/Syfaro/telegram-bot-api.(*BotAPI).UpdatesChan
	$GOPATH/src/github.com/Syfaro/telegram-bot-api/updates.go:34 +0x12e

goroutine 9 [IO wait]:
net.(*pollDesc).Wait(0xc2080101b0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080101b0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010150, 0xc208030800, 0x400, 0x400, 0x0, 0x611ae0, 0xc2082674e8)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208036048, 0xc208030800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20803ac90, 0x612ec0, 0xc208036048, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208072000, 0x17, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208072000, 0xc20809c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x6179d8, 0xc208072000, 0xc20806e058, 0xc20809c000, 0x1000, 0x1000, 0x257600, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20825f6a0, 0xc20809c000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20826b4a0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20826b4a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20806e000)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc20806e000)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:661 +0xcbc
exit status 2

```

**Comment by Syfaro** [comment]
If you log `telegram.Bot` at line 10 of `example/main.go`, it appears to be `nil`.

This code does work: 

`example/telegram/telegram.go`
```go
package telegram

import (
    "log"

    "github.com/Syfaro/telegram-bot-api"
)

func GetBot() *tgbotapi.BotAPI {
    bot, err := tgbotapi.NewBotAPI("MyToken")
    if err != nil {
        log.Panic(err)
    }

    u := tgbotapi.NewUpdate(0)
    u.Timeout = 60

    err = bot.UpdatesChan(u)
    if err != nil {
        log.Panic(err)
    }

    log.Printf("Authorized on account %s", bot.Self.UserName)

    return bot
}
```

`example/main.go`
```go
package main

import (
    "log"

    "github.com/pyed/example/telegram"
)

func main() {
    bot := telegram.GetBot()

    log.Printf("%+v", bot)

    for update := range bot.Updates {
        log.Printf("[%s] %s", update.Message.From.UserName, update.Message.Text)
    }
}
```

**Comment by pyed** [comment]
@Syfaro sure this will work, but `Bot` will not be available at the `telegram` package scope, and doing the following will also not work.

`example/telegram/telegram.go`
```Go
package telegram

import (
    "log"

    "github.com/Syfaro/telegram-bot-api"
)

var bot *tgbotapi.BotAPI
func GetBot() *tgbotapi.BotAPI {
    bot, err := tgbotapi.NewBotAPI("MyToken")
    if err != nil {
        log.Panic(err)
    }

    u := tgbotapi.NewUpdate(0)
    u.Timeout = 60

    err = bot.UpdatesChan(u)
    if err != nil {
        log.Panic(err)
    }

    log.Printf("Authorized on account %s", bot.Self.UserName)

    return bot
}

func SendMessage(c int, msg string) {
	// create a message config to send it
	newMsg := tgbotapi.NewMessage(c, msg)

	// send the message
	bot.SendMessage(newMsg)
}
```Go

`main.go`

```Go
package main

import (
    "log"

    "github.com/pyed/example/telegram"
)

func main() {
    bot := telegram.GetBot()

    log.Printf("%+v", bot)

    for update := range bot.Updates {
        log.Printf("[%s] %s", update.Message.From.UserName, update.Message.Text)
        telegram.SendMessage(update.Message.Chat.ID, "Got your message!")

    }
}
```

as soon as you send a message to this bot, it will crash with a nil pointer

**Comment by Syfaro** [comment]
Is there something I can do in this library to fix this?

**Comment by pyed** [comment]
I'm not sure

**Comment by Syfaro** [comment]
As it appears this issue isn't related to this project, I'm gonna close it. If you need anything in this project updated to make it easier to use, I can reopen it as needed. 

I wish you luck on figuring this out.
