### ISSUE TITLE
Falling Down while getting Error "502 Bad Gateway"

### ISSUE THREAD

**Issue by alex-savin** [Syfaro/telegram-bot-api#14]
```log
2015/08/09 09:10:50 getUpdates: []
2015/08/09 09:11:10 getUpdates {"ok":true,"result":[]}
2015/08/09 09:11:10 getUpdates: []
2015/08/09 09:11:30 getUpdates {"ok":true,"result":[]}
2015/08/09 09:11:30 getUpdates: []
2015/08/09 09:11:38 getUpdates <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

panic: 

goroutine 11 [running]:
github.com/Syfaro/telegram-bot-api.func·001()
	/root/go/src/github.com/Syfaro/telegram-bot-api/updates.go:17 +0xd5
created by github.com/Syfaro/telegram-bot-api.(*BotAPI).UpdatesChan
	/root/go/src/github.com/Syfaro/telegram-bot-api/updates.go:34 +0x12e

goroutine 1 [chan receive, 607 minutes]:
main.main()
	/usr/local/src/freeswitch_golang_scripts/telegram.go:26 +0x3e4

goroutine 17 [syscall, 628 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 101 [runnable]:
net/http.(*persistConn).readLoop(0xc208076bb0)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 102 [select]:
net/http.(*persistConn).writeLoop(0xc208076bb0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by Syfaro** [comment]
I was getting this too, I think it was an issue related to Telegram's servers. 

It is now working for me, are you still having issues?

**Comment by alex-savin** [comment]
Yes, I'm still having it. Probably one time a day.

**Comment by Syfaro** [comment]
I'm going to change the code so that in debug mode it doesn't panic when an update fails, and that should prevent any more crashes.

**Comment by alex-savin** [comment]
Thank you
